// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY6oimq6Kb6aIejeX1LfnqMeFpHFwGpdU',
    appId: '1:1043786061729:web:845488883de35b62179de0',
    messagingSenderId: '1043786061729',
    projectId: 'pickle-62284',
    authDomain: 'pickle-62284.firebaseapp.com',
    storageBucket: 'pickle-62284.firebasestorage.app',
    measurementId: 'G-1ZR1DGWV3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJtvjo_P2bQMB88wS7Jyn0rsms2przo_4',
    appId: '1:1043786061729:android:d3a13d02f009b22d179de0',
    messagingSenderId: '1043786061729',
    projectId: 'pickle-62284',
    storageBucket: 'pickle-62284.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANc-mafFUdpT465ExsZQkyJJAGMrVtK1s',
    appId: '1:1043786061729:ios:7e4fa56f87c45cd1179de0',
    messagingSenderId: '1043786061729',
    projectId: 'pickle-62284',
    storageBucket: 'pickle-62284.firebasestorage.app',
    iosClientId: '1043786061729-ppsf8v9fbua9sp17ls7u20k32e75tdj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pickle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANc-mafFUdpT465ExsZQkyJJAGMrVtK1s',
    appId: '1:1043786061729:ios:7e4fa56f87c45cd1179de0',
    messagingSenderId: '1043786061729',
    projectId: 'pickle-62284',
    storageBucket: 'pickle-62284.firebasestorage.app',
    iosClientId: '1043786061729-ppsf8v9fbua9sp17ls7u20k32e75tdj9.apps.googleusercontent.com',
    iosBundleId: 'com.example.pickle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDY6oimq6Kb6aIejeX1LfnqMeFpHFwGpdU',
    appId: '1:1043786061729:web:5bc0eb9c59b8bfea179de0',
    messagingSenderId: '1043786061729',
    projectId: 'pickle-62284',
    authDomain: 'pickle-62284.firebaseapp.com',
    storageBucket: 'pickle-62284.firebasestorage.app',
    measurementId: 'G-9ZYJ7TR2W7',
  );

}